language: python
python::
  - "2.7"
  - "3.7"
  - "3.7.1"
  
install: 
  - python -m pip install pipreqs
  - python -m pip install pytest-cov
  
script: 
  - python -m pytest --cov
  - python -m pip freeze > requirements.txt

after_success: coveralls