language: python
python::
  - "2.7"
  - "3.7"
  - "3.7.1"
install: 
  - python -m pip install -r requirements.txt
  - python -m pip install pytest-cov
  
script: 
  - python -m pytest --cov

after_success: coveralls